function Hd = BPF1
%BPF1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 11-Apr-2021 15:58:34

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 128;  % Sampling Frequency

N    = 1000;     % Order
Fc1  = 0.8;      % First Cutoff Frequency
Fc2  = 30;       % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
